--
-- XXL-JOB PostgreSQL 15+ schema
-- Copyright (c) 2015-present, xuxueli.
--

CREATE TABLE xxl_job_group
(
    id           integer generated by default as identity,
    app_name     varchar(64) NOT NULL,
    title        varchar(64) NOT NULL,
    address_type smallint    NOT NULL DEFAULT 0,
    address_list text,
    update_time  timestamp            DEFAULT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE xxl_job_registry
(
    id             bigint generated by default as identity,
    registry_group varchar(50)  NOT NULL,
    registry_key   varchar(255) NOT NULL,
    registry_value varchar(255) NOT NULL,
    update_time    timestamp DEFAULT NULL,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX i_g_k_v ON xxl_job_registry (registry_group, registry_key, registry_value);

CREATE TABLE xxl_job_info
(
    id                        integer generated by default as identity,
    job_group                 integer      NOT NULL,
    job_desc                  varchar(255) NOT NULL,
    add_time                  timestamp             DEFAULT NULL,
    update_time               timestamp             DEFAULT NULL,
    author                    varchar(64)           DEFAULT NULL,
    alarm_email               varchar(255)          DEFAULT NULL,
    schedule_type             varchar(50)  NOT NULL DEFAULT 'NONE',
    schedule_conf             varchar(128)          DEFAULT NULL,
    misfire_strategy          varchar(50)  NOT NULL DEFAULT 'DO_NOTHING',
    executor_route_strategy   varchar(50)           DEFAULT NULL,
    executor_handler          varchar(255)          DEFAULT NULL,
    executor_param            text                  DEFAULT NULL,
    executor_block_strategy   varchar(50)           DEFAULT NULL,
    executor_timeout          integer      NOT NULL DEFAULT 0,
    executor_fail_retry_count integer      NOT NULL DEFAULT 0,
    glue_type                 varchar(50)  NOT NULL,
    glue_source               text,
    glue_remark               varchar(128)          DEFAULT NULL,
    glue_updatetime           timestamp             DEFAULT NULL,
    child_jobid               varchar(255)          DEFAULT NULL,
    trigger_status            smallint     NOT NULL DEFAULT 0,
    trigger_last_time         bigint       NOT NULL DEFAULT 0,
    trigger_next_time         bigint       NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);

CREATE TABLE xxl_job_logglue
(
    id          integer generated by default as identity,
    job_id      integer     NOT NULL,
    glue_type   varchar(50) DEFAULT NULL,
    glue_source text,
    glue_remark varchar(128) NOT NULL,
    add_time    timestamp   DEFAULT NULL,
    update_time timestamp   DEFAULT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE xxl_job_log
(
    id                        bigint generated by default as identity,
    job_group                 integer      NOT NULL,
    job_id                    integer      NOT NULL,
    executor_address          varchar(255) DEFAULT NULL,
    executor_handler          varchar(255) DEFAULT NULL,
    executor_param            text         DEFAULT NULL,
    executor_sharding_param   varchar(20)  DEFAULT NULL,
    executor_fail_retry_count integer      NOT NULL DEFAULT 0,
    trigger_time              timestamp    DEFAULT NULL,
    trigger_code              integer      NOT NULL,
    trigger_msg               text,
    handle_time               timestamp    DEFAULT NULL,
    handle_code               integer      NOT NULL,
    handle_msg                text,
    alarm_status              smallint     NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);
CREATE INDEX I_trigger_time ON xxl_job_log (trigger_time);
CREATE INDEX I_handle_code ON xxl_job_log (handle_code);
CREATE INDEX I_jobgroup ON xxl_job_log (job_group);
CREATE INDEX I_jobid ON xxl_job_log (job_id);

CREATE TABLE xxl_job_log_report
(
    id            integer generated by default as identity,
    trigger_day   timestamp            DEFAULT NULL,
    running_count integer     NOT NULL DEFAULT 0,
    suc_count     integer     NOT NULL DEFAULT 0,
    fail_count    integer     NOT NULL DEFAULT 0,
    update_time   timestamp            DEFAULT NULL,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX i_trigger_day ON xxl_job_log_report (trigger_day);

CREATE TABLE xxl_job_lock
(
    lock_name varchar(50) NOT NULL,
    PRIMARY KEY (lock_name)
);

CREATE TABLE xxl_job_user
(
    id         integer generated by default as identity,
    username   varchar(50)  NOT NULL,
    password   varchar(100) NOT NULL,
    token      varchar(100) DEFAULT NULL,
    role       smallint     NOT NULL,
    permission varchar(255) DEFAULT NULL,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX i_username ON xxl_job_user (username);

INSERT INTO xxl_job_group(id, app_name, title, address_type, address_list, update_time)
VALUES (1, 'xxl-job-executor-sample', '通用执行器Sample', 0, NULL, now()),
       (2, 'xxl-job-executor-sample-ai', 'AI执行器Sample', 0, NULL, now());

INSERT INTO xxl_job_info(id, job_group, job_desc, add_time, update_time, author, alarm_email,
                         schedule_type, schedule_conf, misfire_strategy, executor_route_strategy,
                         executor_handler, executor_param, executor_block_strategy, executor_timeout,
                         executor_fail_retry_count, glue_type, glue_source, glue_remark, glue_updatetime,
                         child_jobid)
VALUES (1, 1, '示例任务01', now(), now(), 'XXL', '', 'CRON', '0 0 0 * * ? *',
        'DO_NOTHING', 'FIRST', 'demoJobHandler', '', 'SERIAL_EXECUTION', 0, 0, 'BEAN', '', 'GLUE代码初始化',
        now(), ''),
       (2, 2, 'Ollama示例任务', now(), now(), 'XXL', '', 'NONE', '',
        'DO_NOTHING', 'FIRST', 'ollamaJobHandler', '{
    "input": "慢SQL问题分析思路",
    "prompt": "你是一个研发工程师，擅长解决技术类问题。",
    "model": "qwen3.5:2b"
}', 'SERIAL_EXECUTION', 0, 0, 'BEAN', '', 'GLUE代码初始化',
        now(), ''),
       (3, 2, 'Dify示例任务', now(), now(), 'XXL', '', 'NONE', '',
        'DO_NOTHING', 'FIRST', 'difyWorkflowJobHandler', '{
    "inputs":{
        "input":"查询班级各学科前三名"
    },
    "user": "xxl-job",
    "baseUrl": "http://localhost/v1",
    "apiKey": "app-OUVgNUOQRIMokfmuJvBJoUTN"
}', 'SERIAL_EXECUTION', 0, 0, 'BEAN', '', 'GLUE代码初始化',
        now(), ''),
       (4, 2, 'OpenClaw示例任务', now(), now(), 'XXL', '', 'NONE', '',
        'DO_NOTHING', 'FIRST', 'openClawJobHandler', '{
    "input": "查看下上海今天得天气，给出出游建议",
    "prompt": "你是一个出游助手，擅长做旅游规划"
}', 'SERIAL_EXECUTION', 0, 0, 'BEAN', '', 'GLUE代码初始化',
        now(), '');

INSERT INTO xxl_job_user(id, username, password, role, permission)
VALUES (1, 'admin', '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92', 1, NULL);

INSERT INTO xxl_job_lock(lock_name)
VALUES ('schedule_lock');

SELECT setval(pg_get_serial_sequence('xxl_job_group', 'id'), COALESCE((SELECT max(id) FROM xxl_job_group), 1), (SELECT count(1) > 0 FROM xxl_job_group));
SELECT setval(pg_get_serial_sequence('xxl_job_registry', 'id'), COALESCE((SELECT max(id) FROM xxl_job_registry), 1), (SELECT count(1) > 0 FROM xxl_job_registry));
SELECT setval(pg_get_serial_sequence('xxl_job_info', 'id'), COALESCE((SELECT max(id) FROM xxl_job_info), 1), (SELECT count(1) > 0 FROM xxl_job_info));
SELECT setval(pg_get_serial_sequence('xxl_job_logglue', 'id'), COALESCE((SELECT max(id) FROM xxl_job_logglue), 1), (SELECT count(1) > 0 FROM xxl_job_logglue));
SELECT setval(pg_get_serial_sequence('xxl_job_log', 'id'), COALESCE((SELECT max(id) FROM xxl_job_log), 1), (SELECT count(1) > 0 FROM xxl_job_log));
SELECT setval(pg_get_serial_sequence('xxl_job_log_report', 'id'), COALESCE((SELECT max(id) FROM xxl_job_log_report), 1), (SELECT count(1) > 0 FROM xxl_job_log_report));
SELECT setval(pg_get_serial_sequence('xxl_job_user', 'id'), COALESCE((SELECT max(id) FROM xxl_job_user), 1), (SELECT count(1) > 0 FROM xxl_job_user));
