package com.xxl.job.admin.db;

import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

class PostgresqlMigrationTest {

    private static final Path ROOT = findRepositoryRoot();

    @Test
    void defaultConfigurationUsesPostgresql() throws IOException {
        String rootPom = read("pom.xml");
        String adminPom = read("xxl-job-admin/pom.xml");
        String applicationProperties = read("xxl-job-admin/src/main/resources/application.properties");
        String compose = read("docker/docker-compose.yml");

        assertTrue(rootPom.contains("<postgresql.version>"));
        assertTrue(rootPom.contains("<artifactId>postgresql</artifactId>"));
        assertTrue(adminPom.contains("<artifactId>postgresql</artifactId>"));
        assertFalse(rootPom.contains("mysql-connector-j"));
        assertFalse(adminPom.contains("mysql-connector-j"));

        assertTrue(applicationProperties.contains("jdbc:postgresql://127.0.0.1:5432/xxl_job"));
        assertTrue(applicationProperties.contains("spring.datasource.driver-class-name=org.postgresql.Driver"));
        assertFalse(applicationProperties.contains("jdbc:mysql:"));
        assertFalse(applicationProperties.contains("com.mysql"));

        assertTrue(compose.contains("postgres:15"));
        assertTrue(compose.contains("pg_isready"));
        assertTrue(compose.contains("jdbc:postgresql://postgres:5432/xxl_job"));
        assertFalse(compose.contains("mysql:"));
    }

    @Test
    void activeDatabaseScriptIsPostgresql() throws IOException {
        String postgresScript = read("doc/db/tables_xxl_job.sql");
        Path mysqlReference = ROOT.resolve("doc/db/tables_xxl_job.mysql.sql");

        assertTrue(Files.exists(mysqlReference));
        assertTrue(postgresScript.contains("generated by default as identity"));
        assertTrue(postgresScript.contains("setval("));
        assertTrue(postgresScript.contains("CREATE UNIQUE INDEX i_g_k_v"));
        assertFalse(postgresScript.contains("AUTO_INCREMENT"));
        assertFalse(postgresScript.contains("ENGINE = InnoDB"));
        assertFalse(postgresScript.contains("DEFAULT CHARSET"));
        assertFalse(postgresScript.contains("`"));
    }

    @Test
    void mapperSqlUsesPostgresqlDialect() throws IOException {
        List<Path> mapperFiles;
        try (var paths = Files.list(ROOT.resolve("xxl-job-admin/src/main/resources/mapper"))) {
            mapperFiles = paths
                    .filter(path -> path.getFileName().toString().endsWith("Mapper.xml"))
                    .toList();
        }

        StringBuilder combined = new StringBuilder();
        for (Path mapperFile : mapperFiles) {
            combined.append(Files.readString(mapperFile)).append('\n');
        }
        String mapperSql = combined.toString();

        assertTrue(mapperSql.contains("LIMIT #{pagesize} OFFSET #{offset}"));
        assertTrue(mapperSql.contains("ON CONFLICT"));
        assertTrue(mapperSql.contains("COALESCE("));
        assertFalse(mapperSql.contains("ON DUPLICATE KEY UPDATE"));
        assertFalse(mapperSql.contains("DATE_ADD("));
        assertFalse(mapperSql.contains("LIMIT #{offset}, #{pagesize}"));
        assertFalse(mapperSql.contains("LIMIT 0,"));
        assertFalse(mapperSql.contains("`"));
        assertFalse(mapperSql.contains("!("));
        assertFalse(mapperSql.contains("IFNULL("));
    }

    private static String read(String relativePath) throws IOException {
        return Files.readString(ROOT.resolve(relativePath));
    }

    private static Path findRepositoryRoot() {
        Path current = Path.of("").toAbsolutePath();
        while (current != null) {
            if (Files.exists(current.resolve("doc/db/tables_xxl_job.sql"))
                    && Files.exists(current.resolve("xxl-job-admin/pom.xml"))) {
                return current;
            }
            current = current.getParent();
        }
        throw new IllegalStateException("Cannot locate repository root");
    }
}
